### ISSUE TITLE
Image URL not working with Star Markup Language

### ISSUE THREAD

**Issue by soerenBoisen** [star-micronics/cloudprnt-sdk#7]
Hello,
We are using cputil to convert Star Document Markup Language for our mC-Print3 printers printing over the CloudPRNT protocol.

We have implemented our own Java-based webapp that implements the protocol using cputil to handle conversion.

It is working fine for text content and QR codes. But we cannot get images to print, even when we try the example from the manual:
```
[align: centre]\
[image: url https://star-emea.com/wp-content/uploads/2015/01/logo.jpg; width 80%; min-width 48mm]\

Image Printing Example

[cut: feed; partial]
```

(taken from [CloudPRNTSDK manual](https://www.star-m.jp/products/s_print/CloudPRNTSDK/Documentation/en/articles/markup/command_image.html?tabs=tabid-2))

What do we need to do to print images?

**Comment by gare-bear** [comment]
@soerenBoisen the markup looks fine so I suspect the issue might be in the arguements you're passing to cputil to manage to conversion. this is typically done by `cputil decode`

could you share the args you're passing to cputil?

**Comment by gare-bear** [comment]
Hi @soerenBoisen, Were you able to fix the issue?

**Comment by gare-bear** [comment]
@soerenBoisen since I haven't heard back from you, i'm closing this issue for now.
